// @ts-check

// One sidebar per product. Each is generated from its folder under docs/, so
// pages are added by creating files (ordering via sidebar_position and
// _category_.json `position`). Cross-product links are injected by the
// sidebarItemsGenerator in docusaurus.config.js (see src/data/products.js).

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  console: [{type: 'autogenerated', dirName: 'console'}],
  llm: [{type: 'autogenerated', dirName: 'llm-gateway'}],
  mcp: [{type: 'autogenerated', dirName: 'mcp-gateway'}],
  agents: [{type: 'autogenerated', dirName: 'workflow-agents'}],
  red: [{type: 'autogenerated', dirName: 'red-teaming'}],
  browser: [{type: 'autogenerated', dirName: 'browser-extension'}],
  endpoint: [{type: 'autogenerated', dirName: 'endpoint-agent'}],
  integ: [{type: 'autogenerated', dirName: 'integrations'}],
};

export default sidebars;
